---
- name: copy the firewall file
  copy: src=${inventory_hostname}.iptables dest=/etc/sysconfig/iptables
  notify: restart iptables

- name: start iptables
  service: name=iptables state=started enabled=yes

